services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Trader2024.
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles

    ports:
      - "8100:8000"
    depends_on:
      - db
    environment:
      DB_NAME: library
      DB_USER: postgres 
      DB_PASSWORD: Trader2024.
      DB_HOST: db
  nginx:
      image: nginx:latest
      ports:
        - "8000:8000"
      networks:
        - backend
  networks:
    backend:
      driver: bridge

volumes:
  postgres_data: